# initialize the version for docker compose
version: '3.7'

services:
  trainer:
    image: keyme-trainer:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./training-data:/app/training-data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia # make sure you have installed nvidia-docker2
              count: 1
              capabilities: [gpu]

    command: ["poetry", "run", "python", "scripts/train_local.py", "--model", "ICNet"]

