name: CI/CD

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'main'  # Runs only if the PR is merged and the base branch is main

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      S3_TRAINING_DATA_BUCKET: ${{ secrets.S3_TRAINING_DATA_BUCKET }}
      TRAINING_TIMEOUT: ${{ secrets.TRAINING_TIMEOUT }}
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal

      - name: Deploy job
        run: |
          modal deploy train_modal.py
